[package]
name = "rocket_tera"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>", "Kunal Mehta <legoktm@debian.org>"]
description = "Tera templating integration for Rocket."
documentation = "https://docs.rs/rocket_tera"
homepage = "https://github.com/legoktm/rocket_tera"
repository = "https://github.com/legoktm/rocket_tera"
readme = "README.md"
keywords = ["rocket", "framework", "templates", "templating", "tera"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.75"

[lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
async_fn_in_trait = "allow"
refining_impl_trait = { level = "allow", priority = -1 }
# unreachable_pub = "warn"
# single_use_lifetimes = "warn"
# missing_docs = "warn"

[lints.clippy]
type_complexity = "allow"
module_inception = "allow"
multiple_bound_locations = "allow"
manual_range_contains = "allow"

[dependencies]
walkdir = "2.4"
notify = "7"
normpath = "1"

tera = "1.19.0"

[dependencies.rocket]
version = "0.5.1"
default-features = false

[dev-dependencies]
pretty_assertions = "1.4"
