[package]
name = "rocket_tera"
version = "1.0.0-rc3"
authors = ["Sergio Benitez <sb@sergio.bz>", "Kunal Mehta <legoktm@debian.org>"]
description = "Tera templating integration for Rocket."
documentation = "https://docs.rs/rocket_tera"
homepage = "https://github.com/legoktm/rocket_tera"
repository = "https://github.com/legoktm/rocket_tera"
readme = "README.md"
keywords = ["rocket", "templates", "templating", "tera"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

[lints.clippy]
all = {level = "deny", priority = -1}
uninlined_format_args = "deny"

[lints.rustdoc]
all = {level = "deny", priority = -1}

[dependencies]
walkdir = "2.4"
notify = "8"
normpath = "1"

tera = "2.3.0"

[dependencies.rocket]
version = "0.5.1"
default-features = false

[dev-dependencies]
pretty_assertions = "1.4"

[[example]]
name = "templating"
test = true
